package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_location") 
@Library("clingo") 
public class clingo_location extends StructObject {
	/**
	 * !< the file where the location begins<br>
	 * C type : const char*
	 */
	@Field(0) 
	public Pointer<Byte > begin_file() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * !< the file where the location begins<br>
	 * C type : const char*
	 */
	@Field(0) 
	public clingo_location begin_file(Pointer<Byte > begin_file) {
		this.io.setPointerField(this, 0, begin_file);
		return this;
	}
	/**
	 * !< the file where the location ends<br>
	 * C type : const char*
	 */
	@Field(1) 
	public Pointer<Byte > end_file() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * !< the file where the location ends<br>
	 * C type : const char*
	 */
	@Field(1) 
	public clingo_location end_file(Pointer<Byte > end_file) {
		this.io.setPointerField(this, 1, end_file);
		return this;
	}
	/** !< the line where the location begins */
	@Ptr 
	@Field(2) 
	public long begin_line() {
		return this.io.getSizeTField(this, 2);
	}
	/** !< the line where the location begins */
	@Ptr 
	@Field(2) 
	public clingo_location begin_line(long begin_line) {
		this.io.setSizeTField(this, 2, begin_line);
		return this;
	}
	/** !< the line where the location ends */
	@Ptr 
	@Field(3) 
	public long end_line() {
		return this.io.getSizeTField(this, 3);
	}
	/** !< the line where the location ends */
	@Ptr 
	@Field(3) 
	public clingo_location end_line(long end_line) {
		this.io.setSizeTField(this, 3, end_line);
		return this;
	}
	/** !< the column where the location begins */
	@Ptr 
	@Field(4) 
	public long begin_column() {
		return this.io.getSizeTField(this, 4);
	}
	/** !< the column where the location begins */
	@Ptr 
	@Field(4) 
	public clingo_location begin_column(long begin_column) {
		this.io.setSizeTField(this, 4, begin_column);
		return this;
	}
	/** !< the column where the location ends */
	@Ptr 
	@Field(5) 
	public long end_column() {
		return this.io.getSizeTField(this, 5);
	}
	/** !< the column where the location ends */
	@Ptr 
	@Field(5) 
	public clingo_location end_column(long end_column) {
		this.io.setSizeTField(this, 5, end_column);
		return this;
	}
	public clingo_location() {
		super();
	}
	public clingo_location(Pointer pointer) {
		super(pointer);
	}
}
