package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_ast_comparison") 
@Library("clingo") 
public class clingo_ast_comparison extends StructObject {
	/** C type : clingo_ast_comparison_operator_t */
	@Field(0) 
	public int comparison() {
		return this.io.getIntField(this, 0);
	}
	/** C type : clingo_ast_comparison_operator_t */
	@Field(0) 
	public clingo_ast_comparison comparison(int comparison) {
		this.io.setIntField(this, 0, comparison);
		return this;
	}
	/** C type : clingo_ast_term_t */
	@Field(1) 
	public clingo_ast_term left() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : clingo_ast_term_t */
	@Field(1) 
	public clingo_ast_comparison left(clingo_ast_term left) {
		this.io.setNativeObjectField(this, 1, left);
		return this;
	}
	/** C type : clingo_ast_term_t */
	@Field(2) 
	public clingo_ast_term right() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : clingo_ast_term_t */
	@Field(2) 
	public clingo_ast_comparison right(clingo_ast_term right) {
		this.io.setNativeObjectField(this, 2, right);
		return this;
	}
	public clingo_ast_comparison() {
		super();
	}
	public clingo_ast_comparison(Pointer pointer) {
		super(pointer);
	}
}
