package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_ast_theory_atom_definition") 
@Library("clingo") 
public class clingo_ast_theory_atom_definition extends StructObject {
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_location location() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_ast_theory_atom_definition location(clingo_location location) {
		this.io.setNativeObjectField(this, 0, location);
		return this;
	}
	/** C type : clingo_ast_theory_atom_definition_type_t */
	@Field(1) 
	public int type() {
		return this.io.getIntField(this, 1);
	}
	/** C type : clingo_ast_theory_atom_definition_type_t */
	@Field(1) 
	public clingo_ast_theory_atom_definition type(int type) {
		this.io.setIntField(this, 1, type);
		return this;
	}
	/** C type : const char* */
	@Field(2) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : const char* */
	@Field(2) 
	public clingo_ast_theory_atom_definition name(Pointer<Byte > name) {
		this.io.setPointerField(this, 2, name);
		return this;
	}
	@Field(3) 
	public int arity() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public clingo_ast_theory_atom_definition arity(int arity) {
		this.io.setIntField(this, 3, arity);
		return this;
	}
	/** C type : const char* */
	@Field(4) 
	public Pointer<Byte > elements() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : const char* */
	@Field(4) 
	public clingo_ast_theory_atom_definition elements(Pointer<Byte > elements) {
		this.io.setPointerField(this, 4, elements);
		return this;
	}
	/** C type : const clingo_ast_theory_guard_definition_t* */
	@Field(5) 
	public Pointer<clingo_ast_theory_guard_definition > guard() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : const clingo_ast_theory_guard_definition_t* */
	@Field(5) 
	public clingo_ast_theory_atom_definition guard(Pointer<clingo_ast_theory_guard_definition > guard) {
		this.io.setPointerField(this, 5, guard);
		return this;
	}
	public clingo_ast_theory_atom_definition() {
		super();
	}
	public clingo_ast_theory_atom_definition(Pointer pointer) {
		super(pointer);
	}
}
