package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_symbolic_literal") 
@Library("clingo") 
public class clingo_symbolic_literal extends StructObject {
	/**
	 * !< the associated symbol (must be a function)<br>
	 * C type : clingo_symbol_t
	 */
	@Field(0) 
	public long symbol() {
		return this.io.getLongField(this, 0);
	}
	/**
	 * !< the associated symbol (must be a function)<br>
	 * C type : clingo_symbol_t
	 */
	@Field(0) 
	public clingo_symbolic_literal symbol(long symbol) {
		this.io.setLongField(this, 0, symbol);
		return this;
	}
	/** !< whether the literal has a sign */
	@Field(1) 
	public boolean positive() {
		return this.io.getBooleanField(this, 1);
	}
	/** !< whether the literal has a sign */
	@Field(1) 
	public clingo_symbolic_literal positive(boolean positive) {
		this.io.setBooleanField(this, 1, positive);
		return this;
	}
	public clingo_symbolic_literal() {
		super();
	}
	public clingo_symbolic_literal(Pointer pointer) {
		super(pointer);
	}
}
