package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Union;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_ast_term") 
@Library("clingo") 
public class clingo_ast_term extends StructObject {
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_location location() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_ast_term location(clingo_location location) {
		this.io.setNativeObjectField(this, 0, location);
		return this;
	}
	/** C type : clingo_ast_term_type_t */
	@Field(1) 
	public int type() {
		return this.io.getIntField(this, 1);
	}
	/** C type : clingo_ast_term_type_t */
	@Field(1) 
	public clingo_ast_term type(int type) {
		this.io.setIntField(this, 1, type);
		return this;
	}
	/** C type : field1_union */
	@Field(2) 
	public clingo_ast_term.field1_union field1() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : field1_union */
	@Field(2) 
	public clingo_ast_term field1(clingo_ast_term.field1_union field1) {
		this.io.setNativeObjectField(this, 2, field1);
		return this;
	}
	/** <i>native declaration : src/main/clingo/lib/c/clingo.h:2078</i> */
	@Name("field1_union") 
	@Union 
	public static class field1_union extends StructObject {
		/** C type : clingo_symbol_t */
		@Field(0) 
		public long symbol() {
			return this.io.getLongField(this, 0);
		}
		/** C type : clingo_symbol_t */
		@Field(0) 
		public field1_union symbol(long symbol) {
			this.io.setLongField(this, 0, symbol);
			return this;
		}
		/** C type : const char* */
		@Field(1) 
		public Pointer<Byte > variable() {
			return this.io.getPointerField(this, 1);
		}
		/** C type : const char* */
		@Field(1) 
		public field1_union variable(Pointer<Byte > variable) {
			this.io.setPointerField(this, 1, variable);
			return this;
		}
		/** C type : const clingo_ast_unary_operation_t* */
		@Field(2) 
		public Pointer<clingo_ast_unary_operation > unary_operation() {
			return this.io.getPointerField(this, 2);
		}
		/** C type : const clingo_ast_unary_operation_t* */
		@Field(2) 
		public field1_union unary_operation(Pointer<clingo_ast_unary_operation > unary_operation) {
			this.io.setPointerField(this, 2, unary_operation);
			return this;
		}
		/** C type : const clingo_ast_binary_operation_t* */
		@Field(3) 
		public Pointer<clingo_ast_binary_operation > binary_operation() {
			return this.io.getPointerField(this, 3);
		}
		/** C type : const clingo_ast_binary_operation_t* */
		@Field(3) 
		public field1_union binary_operation(Pointer<clingo_ast_binary_operation > binary_operation) {
			this.io.setPointerField(this, 3, binary_operation);
			return this;
		}
		/** C type : const clingo_ast_interval_t* */
		@Field(4) 
		public Pointer<clingo_ast_interval > interval() {
			return this.io.getPointerField(this, 4);
		}
		/** C type : const clingo_ast_interval_t* */
		@Field(4) 
		public field1_union interval(Pointer<clingo_ast_interval > interval) {
			this.io.setPointerField(this, 4, interval);
			return this;
		}
		/** C type : const clingo_ast_function_t* */
		@Field(5) 
		public Pointer<clingo_ast_function > function() {
			return this.io.getPointerField(this, 5);
		}
		/** C type : const clingo_ast_function_t* */
		@Field(5) 
		public field1_union function(Pointer<clingo_ast_function > function) {
			this.io.setPointerField(this, 5, function);
			return this;
		}
		/** C type : const clingo_ast_function_t* */
		@Field(6) 
		public Pointer<clingo_ast_function > external_function() {
			return this.io.getPointerField(this, 6);
		}
		/** C type : const clingo_ast_function_t* */
		@Field(6) 
		public field1_union external_function(Pointer<clingo_ast_function > external_function) {
			this.io.setPointerField(this, 6, external_function);
			return this;
		}
		/** C type : const clingo_ast_pool_t* */
		@Field(7) 
		public Pointer<clingo_ast_pool > pool() {
			return this.io.getPointerField(this, 7);
		}
		/** C type : const clingo_ast_pool_t* */
		@Field(7) 
		public field1_union pool(Pointer<clingo_ast_pool > pool) {
			this.io.setPointerField(this, 7, pool);
			return this;
		}
		public field1_union() {
			super();
		}
		public field1_union(Pointer pointer) {
			super(pointer);
		}
	};
	public clingo_ast_term() {
		super();
	}
	public clingo_ast_term(Pointer pointer) {
		super(pointer);
	}
}
