package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.ann.Union;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_ast_statement") 
@Library("clingo") 
public class clingo_ast_statement extends StructObject {
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_location location() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_ast_statement location(clingo_location location) {
		this.io.setNativeObjectField(this, 0, location);
		return this;
	}
	/** C type : clingo_ast_statement_type_t */
	@Field(1) 
	public int type() {
		return this.io.getIntField(this, 1);
	}
	/** C type : clingo_ast_statement_type_t */
	@Field(1) 
	public clingo_ast_statement type(int type) {
		this.io.setIntField(this, 1, type);
		return this;
	}
	/** C type : field1_union */
	@Field(2) 
	public clingo_ast_statement.field1_union field1() {
		return this.io.getNativeObjectField(this, 2);
	}
	/** C type : field1_union */
	@Field(2) 
	public clingo_ast_statement field1(clingo_ast_statement.field1_union field1) {
		this.io.setNativeObjectField(this, 2, field1);
		return this;
	}
	/** <i>native declaration : src/main/clingo/lib/c/clingo.h:2593</i> */
	@Name("field1_union") 
	@Union 
	public static class field1_union extends StructObject {
		/** C type : const clingo_ast_rule_t* */
		@Field(0) 
		public Pointer<clingo_ast_rule > rule() {
			return this.io.getPointerField(this, 0);
		}
		/** C type : const clingo_ast_rule_t* */
		@Field(0) 
		public field1_union rule(Pointer<clingo_ast_rule > rule) {
			this.io.setPointerField(this, 0, rule);
			return this;
		}
		/** C type : const clingo_ast_definition_t* */
		@Field(1) 
		public Pointer<clingo_ast_definition > definition() {
			return this.io.getPointerField(this, 1);
		}
		/** C type : const clingo_ast_definition_t* */
		@Field(1) 
		public field1_union definition(Pointer<clingo_ast_definition > definition) {
			this.io.setPointerField(this, 1, definition);
			return this;
		}
		/** C type : const clingo_ast_show_signature_t* */
		@Field(2) 
		public Pointer<clingo_ast_show_signature > show_signature() {
			return this.io.getPointerField(this, 2);
		}
		/** C type : const clingo_ast_show_signature_t* */
		@Field(2) 
		public field1_union show_signature(Pointer<clingo_ast_show_signature > show_signature) {
			this.io.setPointerField(this, 2, show_signature);
			return this;
		}
		/** C type : const clingo_ast_show_term_t* */
		@Field(3) 
		public Pointer<clingo_ast_show_term > show_term() {
			return this.io.getPointerField(this, 3);
		}
		/** C type : const clingo_ast_show_term_t* */
		@Field(3) 
		public field1_union show_term(Pointer<clingo_ast_show_term > show_term) {
			this.io.setPointerField(this, 3, show_term);
			return this;
		}
		/** C type : const clingo_ast_minimize_t* */
		@Field(4) 
		public Pointer<clingo_ast_minimize > minimize() {
			return this.io.getPointerField(this, 4);
		}
		/** C type : const clingo_ast_minimize_t* */
		@Field(4) 
		public field1_union minimize(Pointer<clingo_ast_minimize > minimize) {
			this.io.setPointerField(this, 4, minimize);
			return this;
		}
		/** C type : const clingo_ast_script_t* */
		@Field(5) 
		public Pointer<clingo_ast_script > script() {
			return this.io.getPointerField(this, 5);
		}
		/** C type : const clingo_ast_script_t* */
		@Field(5) 
		public field1_union script(Pointer<clingo_ast_script > script) {
			this.io.setPointerField(this, 5, script);
			return this;
		}
		/** C type : const clingo_ast_program_t* */
		@Field(6) 
		public Pointer<clingo_ast_program > program() {
			return this.io.getPointerField(this, 6);
		}
		/** C type : const clingo_ast_program_t* */
		@Field(6) 
		public field1_union program(Pointer<clingo_ast_program > program) {
			this.io.setPointerField(this, 6, program);
			return this;
		}
		/** C type : const clingo_ast_external_t* */
		@Field(7) 
		public Pointer<clingo_ast_external > external() {
			return this.io.getPointerField(this, 7);
		}
		/** C type : const clingo_ast_external_t* */
		@Field(7) 
		public field1_union external(Pointer<clingo_ast_external > external) {
			this.io.setPointerField(this, 7, external);
			return this;
		}
		/** C type : const clingo_ast_edge_t* */
		@Field(8) 
		public Pointer<clingo_ast_edge > edge() {
			return this.io.getPointerField(this, 8);
		}
		/** C type : const clingo_ast_edge_t* */
		@Field(8) 
		public field1_union edge(Pointer<clingo_ast_edge > edge) {
			this.io.setPointerField(this, 8, edge);
			return this;
		}
		/** C type : const clingo_ast_heuristic_t* */
		@Field(9) 
		public Pointer<clingo_ast_heuristic > heuristic() {
			return this.io.getPointerField(this, 9);
		}
		/** C type : const clingo_ast_heuristic_t* */
		@Field(9) 
		public field1_union heuristic(Pointer<clingo_ast_heuristic > heuristic) {
			this.io.setPointerField(this, 9, heuristic);
			return this;
		}
		/** C type : const clingo_ast_project_t* */
		@Field(10) 
		public Pointer<clingo_ast_project > project_atom() {
			return this.io.getPointerField(this, 10);
		}
		/** C type : const clingo_ast_project_t* */
		@Field(10) 
		public field1_union project_atom(Pointer<clingo_ast_project > project_atom) {
			this.io.setPointerField(this, 10, project_atom);
			return this;
		}
		/** C type : clingo_signature_t */
		@Field(11) 
		public long project_signature() {
			return this.io.getLongField(this, 11);
		}
		/** C type : clingo_signature_t */
		@Field(11) 
		public field1_union project_signature(long project_signature) {
			this.io.setLongField(this, 11, project_signature);
			return this;
		}
		/** C type : const clingo_ast_theory_definition_t* */
		@Field(12) 
		public Pointer<clingo_ast_theory_definition > theory_definition() {
			return this.io.getPointerField(this, 12);
		}
		/** C type : const clingo_ast_theory_definition_t* */
		@Field(12) 
		public field1_union theory_definition(Pointer<clingo_ast_theory_definition > theory_definition) {
			this.io.setPointerField(this, 12, theory_definition);
			return this;
		}
		public field1_union() {
			super();
		}
		public field1_union(Pointer pointer) {
			super(pointer);
		}
	};
	public clingo_ast_statement() {
		super();
	}
	public clingo_ast_statement(Pointer pointer) {
		super(pointer);
	}
}
