package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_ast_csp_product_term") 
@Library("clingo") 
public class clingo_ast_csp_product_term extends StructObject {
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_location location() {
		return this.io.getNativeObjectField(this, 0);
	}
	/** C type : clingo_location_t */
	@Field(0) 
	public clingo_ast_csp_product_term location(clingo_location location) {
		this.io.setNativeObjectField(this, 0, location);
		return this;
	}
	/** C type : clingo_ast_term_t */
	@Field(1) 
	public clingo_ast_term coefficient() {
		return this.io.getNativeObjectField(this, 1);
	}
	/** C type : clingo_ast_term_t */
	@Field(1) 
	public clingo_ast_csp_product_term coefficient(clingo_ast_term coefficient) {
		this.io.setNativeObjectField(this, 1, coefficient);
		return this;
	}
	/** C type : const clingo_ast_term_t* */
	@Field(2) 
	public Pointer<clingo_ast_term > variable() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : const clingo_ast_term_t* */
	@Field(2) 
	public clingo_ast_csp_product_term variable(Pointer<clingo_ast_term > variable) {
		this.io.setPointerField(this, 2, variable);
		return this;
	}
	public clingo_ast_csp_product_term() {
		super();
	}
	public clingo_ast_csp_product_term(Pointer pointer) {
		super(pointer);
	}
}
