package org.lorislab.clingo4j.api.c;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
/**
 * <i>native declaration : src/main/clingo/lib/c/clingo.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("clingo_ast_show_signature") 
@Library("clingo") 
public class clingo_ast_show_signature extends StructObject {
	/** C type : clingo_signature_t */
	@Field(0) 
	public long signature() {
		return this.io.getLongField(this, 0);
	}
	/** C type : clingo_signature_t */
	@Field(0) 
	public clingo_ast_show_signature signature(long signature) {
		this.io.setLongField(this, 0, signature);
		return this;
	}
	@Field(1) 
	public boolean csp() {
		return this.io.getBooleanField(this, 1);
	}
	@Field(1) 
	public clingo_ast_show_signature csp(boolean csp) {
		this.io.setBooleanField(this, 1, csp);
		return this;
	}
	public clingo_ast_show_signature() {
		super();
	}
	public clingo_ast_show_signature(Pointer pointer) {
		super(pointer);
	}
}
